# The "display name", shown in the GitHub UI
name: Build and test

# Trigger, run on push on any branch
on:
  pull_request:


jobs:
  lint:
    name: "Lint application"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"
  test:
    name: "Build application"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      # Shell script to print the version
      - run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
